### ISSUE TITLE
你好，关于kkpaer 一个页面多次使用，你修改的代码在哪里

### ISSUE THREAD

**Issue by zhaocun6592** [robin-niu/robin-niu.github.io#1]
你好，关于kkpaer 一个页面多次使用，你修改的代码在哪里

**Comment by robin-niu** [comment]
这个好久了。 都忘记修改的哪里了。

**Comment by robin-niu** [comment]
有个地方可以看到：https://github.com/robin-niu/kkpager
在我的commit里：79a8f3352fdd1f72ea5ee4b52464ee7714f78926
